# basic options
title: John's home page
author: John Boniello
email: johnboniello@gmail.com
description: My home page
twitter_username: johnboniello
github_username:  johnboniello

# Build settings
markdown: kramdown
theme: minima
